apiVersion: v1
kind: Pod
metadata:
  name: kuard-with-tls
spec:
  containers:
    - name: kuard-with-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      volumeMounts: # Point de montage des données du secret
      - name: tls-certs # Nom du volume
        mountPath: "/tls" # Chemin de montage
  volumes:
    - name: tls-certs # Nom du volume
      secret:
        secretName: kuard-tls # Nom du secret