apiVersion: v1
kind: Pod
metadata:
  name: mongo-with-volume
spec:
  volumes:
    - name: mongodb-data # Nom du Volume à référencer en bas dans volumeMounts
      azureDisk: # Définition du Azure Disk distant
        kind: Managed
        diskName: formationk8sdisk
        diskURI: $USER_DISK_URI
  containers:
    - image: mongo:3.6
      name: mongodb
      volumeMounts: # Définition du point de montage du volume défini plus haut
        - name: mongodb-data
          mountPath: /data/db
