apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv
spec:
  capacity:
    storage: 2Gi # Capacité du volume
  accessModes: # Mode d'accès
    - ReadWriteOnce
  azureDisk: # Définition du Azure Disk distant
    kind: Managed
    diskName: formationk8sdisk
    diskURI: /subscriptions/ce80d183-bf52-4113-8097-6dad78c8fdb0/resourceGroups/MC_formation-k8s-cluster_k8s-cluster_francecentral/providers/Microsoft.Compute/disks/formationk8sdisk
