apiVersion: v1
kind: PersistentVolume
metadata:
  name: azure-disk-pv
spec:
  capacity:
    storage: 1Gi # Capacité du volume
  accessModes: # Mode d'accès
    - ReadWriteOnce
  azureDisk: # Définition du Azure Disk distant
    kind: Managed
    diskName: formationk8sdisk
    diskURI: $USER_DISK_URI
