apiVersion: v1
kind: Pod
metadata:
  name: mongo-with-pvc
spec:
  volumes:
    - name: mongodb-data
      persistentVolumeClaim: # PVC à utiliser
        claimName: pvc
  containers:
    - image: mongo:3.6
      name: mongodb
      volumeMounts: # Définition du point de montage du PVC défini plus haut
        - name: mongodb-data
          mountPath: /data/db
