apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-storage-class
spec:
  accessModes: # Mode d'accès
    - ReadWriteOnce
  storageClassName: azurefile-storage-class # StorageClass à utiliser pour demander du stockage sur Azure
  resources: # Montant de stockage demandé
    requests:
      storage: 1Gi
