apiVersion: v1
kind: Service
metadata:
  name: kuard-clusterip-service # Nom du service
spec:
  type: ClusterIP # Type du service
  selector: # Selecteur utilisé pour se lier aux pods qui respectent la condition
    app: kuard
  ports:
  - port: 8888 # Port du service
    targetPort: 8080 # Port du conteneur cible