apiVersion: v1
kind: Service
metadata:
  name: kuard-loadbalancer-service # Nom du service
spec:
  type: LoadBalancer # Type du service
  selector: # Selecteur utilisé pour se lier aux pods qui respectent la condition
    app: kuard
  ports:
  - port: 80 # Port du service
    targetPort: 8080 # Port du conteneur cible
    nodePort: 30124 # Port utilisé par le service sur tout les noeuds